name: rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core tools
  - python>=3.9
  - star
  - trinity
  - rsem
  - bowtie2
  - samtools>=1.3
  - subread
  
  # QC tools
  - fastqc
  - multiqc
  - fastp
  
  # Python packages
  - pandas>=1.3.0
  - numpy>=1.20.0
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0
  - pip
  - pip:
    - pydeseq2
  
  # Sequence analysis
  - entrez-direct
  - blast
  - hmmer
  - emboss


